flowchart TD

subgraph RAG_pipeline

    A[User submits a question] 
    A --> O         
    A --> B   
    M[combine, condense 
        the query using 
        history and context create 
        request for completions 
    to LLM ] --> Z
    E --> M
    I --> M
    L --> M

    subgraph Response_Generation
        
        Z[LLM: Generates 
        Context-aware Response] 
        N[Output Answer, 
        Reference to Chunks, 
        Metadata]
        Z --> N 

    end 

    subgraph Session_Context
        
        O[Previous Session Context: 
        using the 
            Chat History in MongoDB 
            up to 
            last 3 messages ]  

        E[Trim history 
            buffer by token count]

        O --> E
        
    end

    subgraph Query_Analysis
        direction TB
        B[Structural analysis: 
        Language Detection 
            & Token Count]
    end

    subgraph Chunk_Retrieval
        direction TB
        B --> H[Similarity Search for 
        Top Chunks in ChromaDB] --> 
        I[Re-rank with FlashRank:
             Cross Encoder 
            returns 3 chunks]

    end

    subgraph Prompt_Template
        direction TB
        L[Language-Specific
         Rules & Instructions]
    end

end

%% Styling

classDef outer fill:#ffffff,stroke:#01579b,stroke-width:1px
classDef blue fill:#e1f5fe,stroke:#01579b,stroke-width:2px

class RAG_pipeline outer
class Response_Generation blue
class Chunk_Retrieval blue
class Session_Context,Query_Analysis,Prompt_Template blue
